[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/creador-horarios/*"
  to = "/creador-horarios/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/creador-horarios/index.html"
  status = 200